#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

copyPgm() {
    local pgm="$1"

    local pgmPath="$(whereis -b $pgm | awk '{ print $2}')"

    # echo "$pgm: -> $pgmPath"
    if [ -z "${pgmPath}" ] ; then
        echo "could not find ${pgmPath}"
    fi

    echo "[balena-init] copy ${pgmPath}"

    copy_exec ${pgmPath}
}

##############################
# main                       #
##############################


# REQUIRED_PGMS="mkdir dd gzip grep awk cp fuser df echo rm reboot sleep partprobe"

if [ -f /etc/balena-migrate.conf ] ; then
    # TODO: move ?
    . /etc/balena-migrate.conf
else
    echo "could not find /etc/balena-migrate.conf"
    exit 1
fi

for pgmName in ${REQUIRED_PGMS}
do
    copyPgm ${pgmName}
done

echo "[balena-init] dest dir ${DESTDIR}"

cp /etc/balena-migrate.conf "${DESTDIR}/etc/"

exit 0
