#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

copyPgm() {
    local pgm="$1"

    local pgmPath="$(whereis -b $pgm | awk '{ print $2}')"

    if [ -z "${pgmPath}" ] ; then
        echo "could not find ${pgmPath}"
    fi

    log "copy ${pgmPath}"

    copy_exec ${pgmPath}
}

log() {
	echo "[$(date +%T) balena-init] $1"
}

fail() {
	echo "[$(date +%T) balena-init] $1"
	echo "[$(date +%T) balena-init] terminating"
	exit 1
}


##############################
# main                       #
##############################


# REQUIRED_PGMS="mkdir dd gzip grep awk cp fuser df echo rm reboot sleep partprobe"

if [ -f /etc/balena-migrate-stage2.conf ] ; then
    # TODO: move ?
    . /etc/balena-migrate-stage2.conf
else
    echo "could not find /etc/balena-migrate-stage2.conf"
    exit 1
fi

for pgmName in ${REQUIRED_PGMS}
do
    copyPgm ${pgmName}
done

log "dest dir ${DESTDIR}"

log "copy /etc/balena-migrate-stage2.conf"
cp /etc/balena-migrate-stage2.conf "${DESTDIR}/etc/"

MIGRATE_DIR="${DESTDIR}${MIGRATE_TMP}"
log "creating migrate dir ${MIGRATE_DIR}"
mkdir -p "$MIGRATE_DIR" || fail "failed to create directory ${MIGRATE_DIR}"
log "...done"

if [ -n "${BALENA_CONFIG}" ] && [ -f "${HOME_DIR}/${BALENA_CONFIG}" ] ; then
	log "copying balena config from ${HOME_DIR}/${BALENA_CONFIG} to ${MIGRATE_DIR}/"
	cp "${HOME_DIR}/${BALENA_CONFIG}" "${MIGRATE_DIR}/" || fail "failed to copy ${HOME_DIR}/${BALENA_CONFIG}  to ${MIGRATE_DIR}/"
	log "..done"
fi

log "copying network config files to initramfs"
for file in $NETWORK_CONFIGS; do
	if [ -f "${HOME_DIR}/$file" ] ; then
		log "copying ${HOME_DIR}/$file"
		cp "${HOME_DIR}/$file" "${MIGRATE_DIR}/" || fail "failed to copy ${HOME_DIR}/$fileto ${MIGRATE_DIR}/"
	else
		fail "could not find  ${HOME_DIR}/$file"
	fi
done

if [ "$GRUB_INSTALL" = "TRUE" ] ; then
	if [ -d /usr/lib/grub ] ; then
		log "copy grub env from /usr/lib/grub"
		mkdir -p ${DESTDIR}/usr/lib/grub
		cp -r /usr/lib/grub/* ${DESTDIR}/usr/lib/grub || fail "failed to copy /usr/lib/grub"
	else
		log "/usr/lib/grub does not exist"
		exit 1
	fi

	if [ -f ${HOME_DIR}/grub.cfg ] ; then
		log "copying ${HOME_DIR}/grub.cfg"
		cp ${HOME_DIR}/grub.cfg "${MIGRATE_DIR}/" || fail "failed to copy ${HOME_DIR}/grub.cfg"
	fi

	if [ -f ${HOME_DIR}/device.map ] ; then
		log "copying ${HOME_DIR}/device.map"
		cp ${HOME_DIR}/device.map "${MIGRATE_DIR}/" || fail "failed to copy ${HOME_DIR}/device.map"
	fi
fi

exit 0
