#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

copyPgm() {
    local pgm="$1"

    local pgmPath="$(whereis -b $pgm | awk '{ print $2}')"

    # echo "$pgm: -> $pgmPath"
    if [ -z "${pgmPath}" ] ; then
        echo "could not find ${pgmPath}"
    fi

    echo "[balena-init] copy ${pgmPath}"

    copy_exec ${pgmPath}
}

##############################
# main                       #
##############################


# REQUIRED_PGMS="mkdir dd gzip grep awk cp fuser df echo rm reboot sleep partprobe"

if [ -f /etc/balena-migrate-stage2.conf ] ; then
    # TODO: move ?
    . /etc/balena-migrate-stage2.conf
else
    echo "could not find /etc/balena-migrate-stage2.conf"
    exit 1
fi

for pgmName in ${REQUIRED_PGMS}
do
    copyPgm ${pgmName}
done

echo "[balena-init] dest dir ${DESTDIR}"

# cp /etc/balena-migrate.conf "${DESTDIR}/etc/"

if [ "$GRUB_INSTALL" = "TRUE" ] ; then
	if [ -d /usr/lib/grub ] ; then
		mkdir -p ${DESTDIR}/usr/lib/grub
		cp -r /usr/lib/grub/* ${DESTDIR}/usr/lib/grub
  fi

	if [ -f ${HOME_DIR}/grub.cfg ] ; then
		echo "[balena-init] copying ${HOME_DIR}/grub.cfg"
		cp ${HOME_DIR}/grub.cfg "${DESTDIR}/"
	fi

	if [ -f ${HOME_DIR}/device.map ] ; then
		echo "[balena-init] copying ${HOME_DIR}/device.map"
		cp ${HOME_DIR}/device.map "${DESTDIR}/"
	fi
fi

exit 0
