#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

set -e

if [ -f /scripts/functions ] ; then
    . /scripts/functions
fi

if [ -f /scripts/local ] ; then
    . /scripts/local
fi

# reboot -f

if [ -f /etc/balena-migrate-stage2.conf ] ; then
    . /etc/balena-migrate-stage2.conf
else
    panic  "/etc/balena-migrate-stage2.conf not found"
fi

if [ -f /scripts/balena-common ] ; then
    . /scripts/balena-common
else
		panic  "/scripts/balena-common not found"
fi

if [  "$STRATEGY" != "DEFAULT" ] ; then
    log "local-premount balena-stage2-default not enabled"
    exit 0
fi

# TODO: make sure required programs are actually present

FAIL_EXIT="panic"

LOG_TO=
log_to "${MIGRATE_TMP}/${LOG_FILE}"

log "local-bottom balena-stage2-default started"

if [ -n "$LOG_DRIVE" ] ; then
	if mount_device ${LOG_DRIVE} ${LOG_FS_TYPE} ${LOG_MOUNT_DIR} ; then
		log_to 	"${LOG_MOUNT_DIR}/${LOG_FILE}"
		UMOUNT_LOG="${LOG_MOUNT_DIR}"
  else
		LOG_DRIVE=
	fi
fi

# TODO: restore former boot configuration on raspian

if [ "$RESTORE_BOOT" = "TRUE" ] ; then
	log "attempting to restore boot configuration"

	if [ "$ORIG_BOOT_PART" != "$ORIG_ROOT_PART" ] ; then
		if ! mount_device ${ORIG_BOOT_PART} ${ORIG_BOOT_FS_TYPE} /orig-boot ; then
		 	log "failed to mount ${ORIG_BOOT_PART}"
		else
			UMOUNT_BOOT=/orig-boot
	 fi
	fi

	if [ -n "$CONFIG_TXT" ] && [ -n "$CONFIG_TXT_BACKUP" ] ; then
		cp /orig-boot/${CONFIG_TXT_BACKUP} /orig-boot/${CONFIG_TXT} >>"$LOG_TO" 2>&1 || log "failed to copy /orig-boot/${CONFIG_TXT_BACKUP}"
		log "copied /orig-boot/${CONFIG_TXT_BACKUP} to /orig-boot/${CONFIG_TXT}"
	fi

	if [ -n "$CMDLINE_TXT" ] && [ -n "$CMDLINE_TXT_BACKUP" ] ; then
		cp /orig-boot/${CMDLINE_TXT_BACKUP} /orig-boot/${CMDLINE_TXT} >>"$LOG_TO" 2>&1 || log "failed to copy /orig-boot/${CMDLINE_TXT_BACKUP}"
		log "copied /orig-boot/${CMDLINE_TXT_BACKUP} to /orig-boot/${CMDLINE_TXT}"
	fi

	if [ -n "$UMOUNT_BOOT" ] ; then
		umount ${UMOUNT_BOOT} >>"$LOG_TO" 2>&1 || fail "failed to unmount ${UMOUNT_BOOT}"
		UMOUNT_BOOT=
	fi

	log "restored original boot configuration"
fi

checkMem

log "creating migrate dir ${MIGRATE_TMP}"
mkdir -p ${MIGRATE_TMP} || fail "failed to create directory ${MIGRATE_TMP}"
if [ ! -d ${MIGRATE_TMP} ] ; then
     fail  "failed to create directory in ${MIGRATE_TMP}"
fi
log "...done"

log "copying image from ${rootmnt}${HOME_DIR}/${IMAGE_FILE} to ${MIGRATE_TMP}/"
cp "${rootmnt}${HOME_DIR}/${IMAGE_FILE}" "${MIGRATE_TMP}/" || fail  "failed to copy ${rootmnt}${HOME_DIR}/${IMAGE_FILE}  to ${MIGRATE_TMP}/"
log "..done"

if [ -n "${BALENA_CONFIG}" ] && [ -f "${rootmnt}${HOME_DIR}/${BALENA_CONFIG}" ] ; then
	log "copying balena config from ${rootmnt}${HOME_DIR}/${BALENA_CONFIG} to ${MIGRATE_TMP}/"
	cp "${rootmnt}${HOME_DIR}/${BALENA_CONFIG}" "${MIGRATE_TMP}/" || fail  "failed to copy ${rootmnt}${HOME_DIR}/${BALENA_CONFIG}  to ${MIGRATE_TMP}/"
	log "..done"
fi

if [ -f "${rootmnt}${HOME_DIR}/${BACKUP_FILE}" ] ; then
	log "copying backup from ${rootmnt}${HOME_DIR}/${BACKUP_FILE} to ${MIGRATE_TMP}/"
	cp "${rootmnt}${HOME_DIR}/${BACKUP_FILE}" "${MIGRATE_TMP}/" || fail  "failed to copy ${rootmnt}${HOME_DIR}/${IMAGE_FILE}  to ${MIGRATE_TMP}/"
	log "..done"
fi

log "copying network config files to initramfs"
if [ -f "${rootmnt}${HOME_DIR}/resin-wifi-01" ] ; then
	cp "${rootmnt}${HOME_DIR}/resin-wifi-01" "${MIGRATE_TMP}/" >>"$LOG_TO" 2>&1  || log "no network config copied"
fi

for file in $NETWORK_CONFIGS; do
	log "copying ${rootmnt}${HOME_DIR}/$file"
	cp "${rootmnt}${HOME_DIR}/$file" "${MIGRATE_TMP}/$file" >>"$LOG_TO" 2>&1  || log "no network config copied"
done

log "creating mountpoint on ${BOOT_MNT_DIR}"
mkdir -p ${BOOT_MNT_DIR} || fail "failed to create directory ${BOOT_MNT_DIR}"
if [ ! -d ${BOOT_MNT_DIR} ] ; then
     fail  "failed to create mount directory in ${BOOT_MNT_DIR}"
fi
log "..done"

log "creating mountpoint on ${DATA_MNT_DIR}"
mkdir -p ${DATA_MNT_DIR}  || fail "failed to create directory ${DATA_MNT_DIR}"
if [ ! -d ${DATA_MNT_DIR} ] ; then
     fail  "failed to create mount directory in ${DATA_MNT_DIR}"
fi
log "..done"

if [ "$NO_FLASH" = "TRUE" ] ; then
	term "terminating prematurely "
	if [ -n "$TERM_EXIT" ] ; then
		$TERM_EXIT
	else
		$ERROR_EXIT
	fi
fi

log "unmounting root"
umount ${rootmnt} || fail  "failed umount ${rootmnt}"
# TODO: remount as third exit ?
FAIL_EXIT="reboot -f"
log "..done"


log "flashing image from ${MIGRATE_TMP}/${IMAGE_FILE} to ${BOOT_DEV} "
log "attempting gzip -d -c ${MIGRATE_TMP}/${IMAGE_FILE} | dd of=${BOOT_DEV} bs=4M \n"
gzip -d -c "${MIGRATE_TMP}/${IMAGE_FILE}" | dd of=${BOOT_DEV} bs=4194304 || fail  "failed with gzip -d -c ${MIGRATE_TMP}/${IMAGE_FILE} | dd of=${BOOT_DEV} bs=4194304"
log "..done"

partprobe $BOOT_DEV >>"$LOG_TO" 2>&1 || fail  "failed to reread partitions on $BOOT_DEV"

# DEVS=$(lsblk)
# log "devices after partprobe: $DEVS"

log "mounting resin-data using: mount -w -t $DATA_PART_TYPE $DATA_PART_NAME $DATA_MNT_DIR"
mount -w -t $DATA_PART_TYPE $DATA_PART_NAME "$DATA_MNT_DIR" >>$LOG_TO 2>&1 || fail  "failed to mount resin-data partition"
UMOUNT_RESIN_DATA="$DATA_MNT_DIR"

if [ -z "$LOG_DRIVE" ] ; then
	log_to "$DATA_MNT_DIR/$LOG_FILE"
fi

log "..done"

if [ -f "${MIGRATE_TMP}/${BACKUP_FILE}" ] ; then
	log "copying backup to resin-data"
	cp "$MIGRATE_TMP/$BACKUP_FILE" "$DATA_MNT_DIR" >>$LOG_TO 2>&1 || fail "failed to create backup"
	sync
	log "...done"
fi

log "mounting resin-boot using: mount -w -t $BOOT_PART_TYPE $BOOT_PART_NAME $BOOT_MNT_DIR"
mount -w -t $BOOT_PART_TYPE $BOOT_PART_NAME "$BOOT_MNT_DIR" >>"$LOG_TO" 2>&1 || fail  "failed to mount resin-boot partition"
UMOUNT_RESIN_BOOT="$BOOT_MNT_DIR"
log "..done"

# copy networking config
log "copying network config to resin-boot "
for file in $NETWORK_CONFIGS; do
	log "copying ${MIGRATE_TMP}/$file"
	cp "${MIGRATE_TMP}/$file" "${BOOT_MNT_DIR}/system-connections/$file" >>"$LOG_TO" 2>&1  || log "no network config copied"
done
log "..done"

if [ -n "$BALENA_CONFIG" ] && [ -f "${MIGRATE_TMP}/${BALENA_CONFIG}" ] ; then
	log "copying balena config to resin-boot "
	cp "${MIGRATE_TMP}/${BALENA_CONFIG}" "${BOOT_MNT_DIR}/config.json" >>"$LOG_TO" 2>&1  || log "no balena config copied"
	log "..done"
fi

if [ "$GRUB_INSTALL" = "TRUE" ] ; then
	log "attempting grub install with type $GRUB_BOOT_TYPE"

	# if [ "${FLASH_BOOTLOADER}" == "TRUE" ] ; then
	# 		inform "flashing boot.img os to ${ORIG_BOOT_DEV}"
	# 		dd if=${BOOT_IMG_FILE} of=${ORIG_BOOT_DEV} conv=fdatasync bs=1
	# 		inform "flashing core.img os to ${ORIG_BOOT_DEV}"
	# 		dd if=${CORE_IMG_FILE} of=${ORIG_BOOT_DEV} conv=fdatasync bs=1 seek=512
	# fi

	if [ "$GRUB_BOOT_TYPE" = "legacy" ] ; then
		# --grub-mkdevicemap=device.map \

		if [ -f grub.cfg ] ; then
			log "copying grub.cfg"
			mkdir -p ${BOOT_MNT_DIR}/grub >>$LOG_TO 2>&1 || fail "failed to create directory ${BOOT_MNT_DIR}/grub"
			cp grub.cfg ${BOOT_MNT_DIR}/grub/ >>$LOG_TO 2>&1 || fail "failed to copy grub.cfg"
		else
			fail "no grub config found"
		fi

		if [ -d "${BOOT_MNT_DIR}/EFI" ]  ; then
			log "deleting ${BOOT_MNT_DIR}/EFI"
			rm -rf ${BOOT_MNT_DIR}/EFI >>"$LOG_TO" 2>&1 || log "failed to delete ${BOOT_MNT_DIR}/EFI"
		fi

		grub-install 	--no-floppy \
									--boot-directory=${BOOT_MNT_DIR} \
									${BOOT_DEV} >>"$LOG_TO" 2>&1 || fail "failed to install grub"
	else
		# 									 \
		log "Add UEFI boot entry for starting resinOS from internal media."

		if [ -f grub.cfg ] ; then
			log "copying grub.cfg"
			cp grub.cfg  ${BOOT_MNT_DIR}/EFI/BOOT/ >>$LOG_TO 2>&1 || fail "failed to copy grub.cfg"
		else
			fail "no grub config found"
		fi

		efibootmgr -c -d ${BOOT_DEV} -p 1 -L "resinOS" -l "\EFI\BOOT\bootx64.efi" || fail "failed to install uefi boot manager with: efibootmgr -c -d ${BOOT_DEV} -p 1 -L resinOS -l \EFI\BOOT\bootx64.efi"
#
#		log "attempting grub-install 	--no-floppy --efi-directory=${BOOT_MNT_DIR} --boot-directory=${BOOT_MNT_DIR}"
#		grub-install 	--no-floppy \
#									--efi-directory=${BOOT_MNT_DIR} \
#									--boot-directory=${BOOT_MNT_DIR} \
#									${BOOT_DEV} >>"$LOG_TO" 2>&1 || fail "failed to install grub"
	fi
fi

if [ -n "$UMOUNT_RESIN_BOOT" ] ; then
	umount $UMOUNT_RESIN_BOOT >>"$LOG_TO" 2>&1 || log "failed to umount $UMOUNT_RESIN_BOOT"
fi

if [ -n "$UMOUNT_RESIN_DATA" ] ; then
	umount $UMOUNT_RESIN_DATA >>"$LOG_TO" 2>&1 || log "failed to umount $UMOUNT_RESIN_DATA"
fi

if [ -n "$UMOUNT_LOG" ] ; then
	umount $UMOUNT_LOG || true
fi

sync || true
reboot -f
