#!/bin/sh

PREREQ="balena-stage2-resized balena-stage2-tmpfs"
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

set -e

if [ -f /scripts/functions ] ; then
    . /scripts/functions
fi

if [ -f /etc/balena-migrate.conf ] ; then
    . /etc/balena-migrate.conf
else
    # TODO: try to rebuild former boot config
    # where is boot mounted
    panic "balena-migrate.conf not found"
fi

log_begin_msg "copying image from ${rootmnt}/${IMAGE_FILE} to ${MIGRATEFS_MOUNT_POINT}"
cp "${rootmnt}/${IMAGE_FILE}" "${MIGRATEFS_MOUNT_POINT}" || panic "failed to copy ${rootmnt}/${IMAGE_FILE} to ${MIGRATEFS_MOUNT_POINT}"
log_end_msg

log_begin_msg "copying backup from ${rootmnt}/${IMAGE_FILE} to ${MIGRATEFS_MOUNT_POINT}"
cp "${rootmnt}/${IMAGE_FILE}" "${MIGRATEFS_MOUNT_POINT}" || panic "failed to copy ${rootmnt}/${IMAGE_FILE} to ${MIGRATEFS_MOUNT_POINT}"
log_end_msg

