#!/bin/bash

set -e


INPUT_IMG=
LOOP_DEV=
MNT_DIR=
TMP_DIR=
GRUB_FILE=
IMG_FILE=
BLOCK_SIZE=512

function fail {
  echo "${1}"
  clean
  exit 1
}

function printHelp {
  echo ""
  echo "extract - extract balena OS image and grub config from balena OS flasher image"
  echo "  USAGE extract [OPTIONS] <image-file>"
  echo "  please run as root."
  echo "  OPTIONS: "
  echo "    --grub=<output grub file> : output grub config to given path"
  echo "    --img=<output image file> : output OS image to given path"
  echo ""
  exit 0
}

function clean {
  if [ -n "$LOOP_DEV" ] && [ -b "$LOOP_DEV" ] ; then
    # echo "removing $LOOP_DEV"
    umount $LOOP_DEV || true
    losetup -d $LOOP_DEV
    LOOP_DEV=
  fi

  if [ -n "$MNT_DIR" ] && [ -d "$MNT_DIR" ] ; then
    # echo "removing mount point $MNT_DIR"
    rmdir "$MNT_DIR"
  fi

  if [ -n "$TMP_DIR" ] && [ -d "$TMP_DIR" ] ; then
    # echo "removing temporary directory $TMP_DIR"
    rm -rf "$TMP_DIR"
  fi
}

function getCmdArgs {
  cmd=
  for var in "$@"
  do
    if [[ ! $var =~ ^-.*$ ]] ; then
      INPUT_IMG="$var"
      echo "using input file: $INPUT_IMG"
      continue
    fi

    if [[ $var =~ ^--grub-boot=.*$ ]] ; then
      GRUB_BOOT_IMG=$(expr match "$var" '^--grub-boot=\(.*\)$')
      echo "using grub boot img output file $GRUB_BOOT_IMG"
      continue
    fi

    if [[ $var =~ ^--grub-core=.*$ ]] ; then
      GRUB_CORE_IMG=$(expr match "$var" '^--grub-core=\(.*\)$')
      echo "using grub boot img output file $GRUB_CORE_IMG"
      continue
    fi

    if [[ $var =~ ^--grub=.*$ ]] ; then
      GRUB_FILE=$(expr match "$var" '^--grub=\(.*\)$')
      echo "using grub output file $GRUB_FILE"
      continue
    fi

    if [[ $var =~ ^--img=.*$ ]] ; then
      IMG_FILE=$(expr match "$var" '^--img=\(.*\)$')
      echo "using image output file $IMG_FILE"
      continue
    fi

    if [[ $var =~ ^(--help|-h)$ ]] ; then
      printHelp
      exit 0
    fi

    fail "unrecognized argument $var"
  done
}



################################################################################
# main
################################################################################

getCmdArgs "$@"

if [[ $EUID -ne 0 ]]; then
  fail "Please run this script as root"
fi

if [ -z "$INPUT_IMG" ] ; then
  echo "ERROR: no input image file given."
  printHelp
  fail
fi

if [ ! -f "$INPUT_IMG" ] ; then
  echo "ERROR file not found $INPUT_IMG"
  printHelp
  fail
fi

if [ -z "$IMG_FILE" ] && [ -z "$GRUB_FILE" ] ; then
  echo "USAGE: extract [--grub=<grub output file>] [--img=<image output file>] <image-file>"
  fail "no output files specified, please use --img and/or --grub options to specify output files"
fi

FTYPE=$(file -b "$INPUT_IMG")

if [[ $FTYPE =~ ^Zip\ archive\ data.* ]]  ; then
  echo "file appears to be a zip archive, unzipping.."
  TMP_DIR=$(mktemp -d -p ./)
  unzip "$INPUT_IMG" -d "$TMP_DIR" || fail "failed to unzip $INPUT_IMG"
  INPUT_IMG="${TMP_DIR}/$(ls "$TMP_DIR")"
  echo "got ${INPUT_IMG}"
  FTYPE=$(file -b "$INPUT_IMG")
fi

if [[ ! $FTYPE =~ ^DOS/MBR\ boot\ sector.* ]]  ; then
  fail "cannot make sense of image file $INPUT_IMG - expecting an image file, got $FTYPE"
fi


if [[ ! "$INPUT_IMG" =~ ^[^\ ]+\.img$ ]] ; then
  fail "cannot make sense of image file $INPUT_IMG - expecting a single file that ends with .img"
fi

echo "processing image $INPUT_IMG"

while read line
do

  if [[ $line =~ ^1:[0-9]+s:.* ]] ; then
    bootStart=$(expr match "$line" '^1:\([0-9]\+\)s')
    bootStart=$(($bootStart*$BLOCK_SIZE))
    # echo "got boot partition start offset $bootStart"
    continue
  fi

  if [[ $line =~ ^2:[0-9]+s:.* ]] ; then
    rootStart=$(expr match "$line" '^2:\([0-9]\+\)s')
    rootStart=$(($rootStart*$BLOCK_SIZE))
    # echo "got root partition start offset $rootStart"
    break
  fi
done < <(parted -sm "$INPUT_IMG" unit s print)

MNT_DIR=$(mktemp -d -p ./)

if [ -n "$GRUB_FILE" ] ; then
  # echo "attempting losetup --show -o $bootStart -f $INPUT_IMG"
  LOOP_DEV=$(losetup --show -o $bootStart -f "$INPUT_IMG") || fail "failed to loopmount boot partition"

  echo "boot partition attached to loop device $LOOP_DEV"

  echo "mounting boot"
  mount $LOOP_DEV "$MNT_DIR"

  cp "${MNT_DIR}/grub.cfg_internal" "$GRUB_FILE" || fail "failed to copy grub config"
  echo "copied ${MNT_DIR}/grub.cfg_internal to $GRUB_FILE"

  if [ -n "$GRUB_BOOT_IMG" ] ; then
    if [ -f "${MNT_DIR}/grub/boot.img ] ; then
      cp "${MNT_DIR}/grub/boot.img "$GRUB_BOOT_IMG"
    else
      fail "cannot find grub/boot.img in flasher boot partition"
    fi
  fi

  if [ -n "$GRUB_CORE_IMG" ] ; then
    if [ -f "${MNT_DIR}/grub/core.img ] ; then
      cp "${MNT_DIR}/grub/core.img "$GRUB_CORE_IMG"
    else
      fail "cannot find grub/core.img in flasher boot partition"
    fi
  fi

  sleep 1 # otherwise mount dir might still be busy...
  umount "$MNT_DIR" || fail "failed to unmount boot partition"
  losetup -d $LOOP_DEV || fail "failed to unmount loop device"
  LOOP_DEV=
fi

if [ -n "$IMG_FILE" ] ; then
  # echo "attempting losetup --show -o $rootStart -f $INPUT_IMG"
  LOOP_DEV=$(losetup --show -o $rootStart -f "$INPUT_IMG") || fail "failed to loopmount boot partition"

  echo "root-A partition attached to loop device $LOOP_DEV"

  echo "mounting root-A"
  mount $LOOP_DEV "$MNT_DIR"

  gzip -c "${MNT_DIR}/opt/resin-image-genericx86-64.resinos-img" > "$IMG_FILE" || fail "failed to copy image file"
  echo "gzipped ${MNT_DIR}/opt/resin-image-genericx86-64.resinos-img to $IMG_FILE"
  sleep 1 # otherwise mount dir might still be busy...

  umount "$MNT_DIR" || fail "failed to unmount root-A partition"
  losetup -d $LOOP_DEV || fail "failed to unmount loop device"
  LOOP_DEV=
fi

clean
