#!/bin/sh


logMsg() {
	if [ -z "$LOG_TO" ] ; then
		fail "logMsg LOG_TO not set"
	fi

	if [ ! -f $LOG_TO ] ; then
		LOG_DIR=$(dirname $LOG_TO)
		if [ ! -d $LOG_DIR ] ; then
			mkdir -p $LOG_DIR	|| fail  "failed to create directory $LOG_DIR"
		fi
  fi

	echo $1 >> "$LOG_TO"
}

log_to() {
  NEW_LOG=$1
  if [ -n "$LOG_TO" ] ; then
    cp "$LOG_TO" "$NEW_LOG"
  fi
  LOG_TO=$NEW_LOG
}

log() {
	logMsg "LOG: $1"
}

term() {
	logMsg "TERM: $1"
	cat "$LOG_TO"
	if [ -n "$UMOUNT_LOG" ] ; then
		umount $UMOUNT_LOG || true
	fi

  if [[ ! $FAIL_EXIT =~ ^\ *reboot ]] ; then
		if [ -n "$TERM_EXIT" ] ; then
			$TERM_EXIT
		else
			$FAIL_EXIT $1
		fi
  else
		$FAIL_EXIT
	fi
}

fail() {
	logMsg "ERROR: $1"
  if [[ ! "$FAIL_EXIT" =~ ^\ *reboot ]] ; then
		log $1
		cat "$LOG_TO"
	fi

	$FAIL_EXIT
}

mount_device() {
	MNT_FS_NAME=$1
	MNT_FS_TYPE=$2
	MNT_DIR=$3
	TOLERATE=$4

	if [ ! -d ${MNT_DIR} ] ; then
	  mkdir -p ${MNT_DIR} || fail "failed to create mount dir ${MNT_DIR}"
	fi

	loopCount=0
	while [ ! -b "${MNT_FS_NAME}" ] && [ $loopCount -lt 3 ] ;
	do
		 log "log device not present: ${MNT_FS_NAME} waiting.."
		 udevadm settle --timeout=10
		 sleep 10
		 loopCount=$(($loopCount + 1))
	done

	if [ -b "${MNT_FS_NAME}" ] ; then
		if ! mount -w -t ${MNT_FS_TYPE} ${MNT_FS_NAME} ${MNT_DIR} >>"$LOG_TO" 2>&1  ; then
		  log "failed to mount device using  mount -w -t ${MNT_FS_TYPE} ${MNT_FS_NAME} ${MNT_DIR}"
			return 1
		else
			log "mounted device ${MNT_FS_NAME} on ${MNT_DIR}"
			return 0
	  fi
	else
		log "device not present: ${MNT_FS_NAME}"
		return 1
	fi
}
