#!/bin/bash

# read { volume: name,
#   contents: [  { sourcePath: "file,dir,wildcard",  targetPath: "dir" }, ..   ]

CSV_FILE=$1

while read -r line
do

  if [[ $line =~ ^([^,]*),(.*)$ ]] ; then
    field=${BASH_REMATCH[1]}
  else
    nop
  fi
done < "$CSV_FILE"
