#!/bin/sh
ENV_SUB=./env_vars
TEST_SUB=./test_sub

if [ -f "$ENV_SUB" ] ; then
  echo "loading $ENV_SUB"
  . "$ENV_SUB"
else
  echo "$ENV_SUB could not be found"
fi

echo "local: $TEST1 $TEST2 $TEST3"

if [ -f "$TEST_SUB" ] ; then
  echo "loading $TEST_SUB"
  . $TEST_SUB
else
  echo "$TEST_SUB could not be found"
fi

test_it
