#!/bin/sh

PREREQ="balena-stage2-resized balena-stage2-tmpfs"
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

set -e

if [ -f /scripts/functions ] ; then
    . /scripts/functions
fi

if [ -f /scripts/local ] ; then
    . /scripts/local
fi

if [ -f /etc/balena-migrate.conf ] ; then
    . /etc/balena-migrate.conf
else
    # TODO: try to rebuild former boot config
    # where is boot mounted
    panic "balena-migrate.conf not found"
fi

log_success_msg "local-premount balena-stage2 started params: $1 $2 $3"

echo "ls: $(ls /dev) \n"

echo "fuser: $(fuser /root) \n"

umount ${rootmnt} || panic "failed umount ${rootmnt}"

echo "df: $(df) \n"

sleep 5

reboot -f
