#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

set -e

exit 0

# MIGRATEFS_MOUNT_POINT="/mnt/balena-migrate"

if [ -f /scripts/functions ] ; then
    . /scripts/functions
fi

if [ -f /scripts/local ] ; then
    . /scripts/local
fi

log_success_msg "init-bottom balena-stage2-resized started"

if [ -f /etc/balena-migrate.conf ] ; then
    . /etc/balena-migrate.conf
else
    panic "balena-migrate.conf not found"
fi

if [ -f /scripts/balena-common ] ; then
    . /scripts/balena-common
else
		panic  "/scripts/balena-common not found"
fi

if [  "$STRATEGY" != "RESIZE" ] ; then
    log_success_msg "local-premount balena-stage2-resized not enabled"
    exit 0
fi

log_begin_msg "creating mountpoint on ${MIGRATEFS_MOUNT_POINT}"

# echo "${NEW_PART_NAME} ${MIGRATEFS_MOUNT_POINT} ${NEW_PART_FS}	defaults	0   2" >> /etc/fstab

mkdir -p ${MIGRATEFS_MOUNT_POINT}
if [ ! -d ${MIGRATEFS_MOUNT_POINT} ] ; then
     panic "failed to create mount directory in ${MIGRATEFS_MOUNT_POINT}"
fi
log_end_msg

# _log_msg "would attempt: mount -t  ${NEW_PART_FS} ${NEW_PART_NAME} ${MIGRATEFS_MOUNT_POINT}"

local_mount_fs "${MIGRATEFS_MOUNT_POINT}" || panic "failed to mount ${MIGRATEFS_MOUNT_POINT}"

_log_msg "$(df)"

# mount -t  "${NEW_PART_FS}" "${NEW_PART_NAME}" "${MIGRATEFS_MOUNT_POINT}" || panic "failed: mount -t  ${NEW_PART_FS} ${NEW_PART_NAME} ${MIGRATEFS_MOUNT_POINT}"

# log_success_msg "mounted ${NEW_PART_NAME}"
